### ISSUE TITLE
Transfer learning setting in supplmentary methods

### ISSUE THREAD

**Issue by madnessfish** [bm2-lab/PanPep#11]
Thank you so much for the excellent work! The work definitely helps the field for unseen prediction.

I am interested in the baseline setting ("it was trained in a conventional manner") in comparison with PanPep. Whether the transfer learning is done by parameter-transfer, instance-transfer, or feature-representation-transfer?

**Comment by GaoYiChengTJ** [comment]
Thanks for your interest! Based on the categories you showed above, our baseline setting may belong to the 'parameter-transfer'.
