### ISSUE TITLE
Input data requirements and model training use

### ISSUE THREAD

**Issue by yanpinlu** [bm2-lab/PanPep#12]
This is a really great job and I have two questions for you:
1. When I use this model to make a prediction, I only have the TCR sequence that I need to predict and I don't know which epitopes to combine with. Do I have to provide epitopes in my input file? And how do I determine which of the three categories my TCR sequence belongs to (few-shot,zero-shot,majority)?
2. What do I do if I want to train my model with my own data set? @ylgao1 @weizhiting

**Comment by GaoYiChengTJ** [comment]
Thanks for your interest. (1) You should provide the candidate epitopes in your input file and the zero-shot setting will be suitable for you. (2) We will push our training code and example data in the future.

**Comment by yanpinlu** [comment]
> Thanks for your interest. (1) You should provide the candidate epitopes in your input file and the zero-shot setting will be suitable for you. (2) We will push our training code and example data in the future.

Thank you very much for your reply and look forward to the early release of the examples and training code

**Comment by XiejcSYSU** [comment]
It's a great job! May I ask when the training code can be released?

**Comment by GaoYiChengTJ** [comment]
Thanks for your interest in our work. Due to some ongoing works related to PanPep, our training code will be made publicly available as soon as possible. We sincerely apologize for any inconvenience this delay may cause. Your understanding and patience are greatly appreciated as we work to ensure the highest quality and usability of our materials.

> It's a great job! May I ask when the training code can be released?
