### ISSUE TITLE
no module named requirements

### ISSUE THREAD

**Issue by dxl3742** [bm2-lab/PanPep#13]
hello, great package!
I'm quite new to python, this is probably a beginner question, any help would be appreciated, thanks in advance!

(panpepp) [chenzhenzhen@localhost panpep]$ pip install requirements-parser
Requirement already satisfied: requirements-parser in /home/chenzhenzhen/.local/lib/python3.9/site-packages (0.5.0)
Requirement already satisfied: types-setuptools>=57.0.0 in /home/chenzhenzhen/.local/lib/python3.9/site-packages (from requirements-parser) (68.2.0.0)
(panpepp) [chenzhenzhen@localhost panpep]$ python PanPep.py --learning_setting few-shot --input ./Data/Example_few-shot.csv --output ./Output/Example_few-shot_output.csv
Traceback (most recent call last):
  File "/home2/chenzhenzhen/panpep/PanPep.py", line 10, in <module>
    from Requirements.Memory_meta import Memory_Meta
ModuleNotFoundError: No module named 'Requirements'

**Comment by dxl3742** [comment]
aah ok figured it out. Thanks！

**Comment by chf8991** [comment]
> aah ok figured it out. Thanks！

I've got the same error. I wonder how did you figure it out, please

**Comment by chf8991** [comment]
> > aah ok figured it out. Thanks！
> 
> I've got the same error. I wonder how did you figure it out, please

Ok, I figured it out. You must firstly cd to the path the PanPep locates
