### ISSUE TITLE
Curated Datasets

### ISSUE THREAD

**Issue by KiAkize** [bm2-lab/PanPep#2]
Hi there,

I was reading through your project and found it to be incredibly helpful for my research. However, I noticed that some datasets mentioned in your paper that are provided with source link. Would it be possible for you to share the **final curated datasets** used in your research?

1) The dataset for Fig.4a and Fig.4b, which contains 10 different unseen neoantigens and their specific experimentally validated TCRs.
2) The dataset for Fig.4c, which contains 68 neoantigens and 1,448 CD8+ T cells with CDR3 beta sequences.
3) The dataset for Fig.5, the large COVID-19 dataset, containing in a total of 1,168,776 peptide–TCR pairs associated with 541 different peptides.

It would be immensely helpful for me to have access to them in order to replicate your results and potentially build upon your work.
Thank you for your time and consideration. Looking forward to hearing back from you.

**Comment by binbinjiang** [comment]
hi man, I am from Westlake University, Hangzhou. I am also interested in this issue/field. Could you please add me, so that we can discuss more? Here is my QQ: 914711123.   Anyone who sees this message and is interested in pMHC-TCR, just feel free to add me.

**Comment by GaoYiChengTJ** [comment]
Hi, thanks for your interest in our work and I am sorry for the delay. All the datasets that we used in our work can be found in the section of data available of our manuscript. I hope this response can solve your question.
