### ISSUE TITLE
Filtering and downloading of training data sets

### ISSUE THREAD

**Issue by yanpinlu** [bm2-lab/PanPep#3]
This is a very good model to learn,  I have two questions:

1. What are the conditions and basis for downloading IEDB database data? What conditions are used to filter the data of the four databases used in the early data processing?

2. The PIRD database is under maintenance, and the data related to TCR epitopes cannot be downloaded. Could you please provide me with the relevant data you used?

My email is 599509779@qq.com
@MichaelChuai @lq19811015 @BinDuan @weizhiting @ylgao1

**Comment by GaoYiChengTJ** [comment]
Hi, thanks for your interest in our work and I am sorry for the delay. The detailed information that we filtered the data can be found in our methods and supplementary information.
