### ISSUE TITLE
ERROR for run zero-shot task

### ISSUE THREAD

**Issue by SZ-qing** [bm2-lab/PanPep#7]
Hello, when i run the zero-shot task, i encounter the error: 
![image](https://github.com/bm2-lab/PanPep/assets/85827219/1c7c4db5-63eb-4074-be15-ffdd99cd7548)

The other two tasks is okey.

**Comment by GaoYiChengTJ** [comment]
Hi, thanks for your interest in our work and I am sorry for the delay. Have you solved this problem? Could you please provide more detailed information about the running process in your device, e.g. the device of your machine.
