### ISSUE TITLE
Can not repeat results in Output

### ISSUE THREAD

**Issue by RysBen** [bm2-lab/PanPep#9]
Hi there,

I ran PanPep with below commands:
```
python PanPep.py     --learning_setting few-shot     --input ./Data/Example_few-shot.csv     --output t1.csv
python PanPep.py     --learning_setting zero-shot     --input ./Data/Example_zero-shot.csv     --output t2.csv
python PanPep.py     --learning_setting majority     --update_step_test 1000     --input ./Data/Example_majority.csv     --output t3.csv
```
Then, I respectively compared `t1.csv`, `t2.csv`, `t3.csv` with `Output/Example_few-shot_output.csv`, `Example_zero-shot_output.csv`, `Example_majority_output.csv`.
However, I could not repeat results in Output, below is the difference:
![image](https://github.com/bm2-lab/PanPep/assets/36749963/1f3b5d91-a88d-4177-8d01-2f229663949e)

Any suggestion would be appreciated.

**Comment by GaoYiChengTJ** [comment]
Hi, thanks for your interest in our work. Based on the very small errors of your results, it seems that this difference may raised by the device or random seed. I hope this response can resolve your question.
